@host = http://localhost:5000
@content-type = application/json

# Shared Variables
@groupId = 0197554f-42c5-7774-94ec-4cf827537e60
@chargeStationId = 0197554f-42c5-75d5-8ddc-d591416dc636
@connectorId = 1

### 1. Create Group
POST {{host}}/api/v1/groups
Content-Type: {{content-type}}

{
  "name": "Test Group",
  "capacityInAmps": 100,
  "chargeStationRequest": {
    "name": "Station A",
    "connectors": [
      {
        "connectorId": 1,
        "maxCurrentInAmps": 30
      },
      {
        "connectorId": 2,
        "maxCurrentInAmps": 20
      }
    ]
  }
}

### 2. Update Group
PUT {{host}}/api/v1/groups/{{groupId}}
Content-Type: {{content-type}}

{
  "name": "Updated Group Name",
  "capacityInAmps": 120
}

### 3. Remove Group
DELETE {{host}}/api/v1/groups/{{groupId}}

### 4. Get Group By Id
GET {{host}}/api/v1/groups/{{groupId}}

### 5. Get Groups By Page
GET {{host}}/api/v1/groups?PageNumber=1&PageSize=5

### 6. Add Charge Station to Group
POST {{host}}/api/v1/groups/{{groupId}}/charge-stations
Content-Type: {{content-type}}

{
  "name": "New Station",
  "connectorsRequest": [
    {
      "connectorId": 1,
      "maxCurrentInAmps": 15
    },
    {
      "connectorId": 2,
      "maxCurrentInAmps": 20
    }
  ]
}

### 7. Remove Charge Station from Group
DELETE {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}

### 8. Update Charge Station Name
PUT {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/name
Content-Type: {{content-type}}

{
  "newName": "Updated Station Name"
}

### 9. Add Connector(s) to Charge Station
POST {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/connectors
Content-Type: {{content-type}}

{
  "connectorsRequest": [
    {
      "connectorId": 3,
      "maxCurrentInAmps": 25
    },
    {
      "connectorId": 4,
      "maxCurrentInAmps": 10
    }
  ]
}

### 10. Remove Connector(s) from Charge Station
DELETE {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/connectors
Content-Type: {{content-type}}

{
  "connectorIds": [1]
}

### 11. Update Connector Max Current
PUT {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/connectors/{{connectorId}}/current
Content-Type: {{content-type}}

{
  "newCurrentInAmps": 40
}