// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCharging.Shared.Application.Data;

#nullable disable

namespace SmartCharging.Shared.Application.Data.Migrations
{
    [DbContext(typeof(SmartChargingDbContext))]
    [Migration("20250604214819_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCharging.Groups.Models.ChargeStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_charge_stations");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_charge_stations_group_id");

                    b.ToTable("charge_stations", (string)null);
                });

            modelBuilder.Entity("SmartCharging.Groups.Models.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ChargeStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("charge_station_id");

                    b.Property<int>("MaxCurrentInAmps")
                        .HasColumnType("integer")
                        .HasColumnName("max_current_in_amps");

                    b.HasKey("Id")
                        .HasName("pk_connectors");

                    b.HasIndex("ChargeStationId")
                        .HasDatabaseName("ix_connectors_charge_station_id");

                    b.ToTable("connectors", (string)null);
                });

            modelBuilder.Entity("SmartCharging.Groups.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CapacityInAmps")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_in_amps");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("SmartCharging.Groups.Models.ChargeStation", b =>
                {
                    b.HasOne("SmartCharging.Groups.Models.Group", null)
                        .WithMany("ChargeStations")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charge_stations_groups_group_id");
                });

            modelBuilder.Entity("SmartCharging.Groups.Models.Connector", b =>
                {
                    b.HasOne("SmartCharging.Groups.Models.ChargeStation", null)
                        .WithMany("Connectors")
                        .HasForeignKey("ChargeStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_connectors_charge_stations_charge_station_id");
                });

            modelBuilder.Entity("SmartCharging.Groups.Models.ChargeStation", b =>
                {
                    b.Navigation("Connectors");
                });

            modelBuilder.Entity("SmartCharging.Groups.Models.Group", b =>
                {
                    b.Navigation("ChargeStations");
                });
#pragma warning restore 612, 618
        }
    }
}
