name: smart-charging-infrastructure

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_HOST_PORT:-5432}:${POSTGRES_PORT:-5432}
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./../configs/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    networks:
      - infrastructure
       
networks:
  infrastructure:
    name: infrastructure
    driver: bridge
    