@host = http://localhost:5000
@content-type = application/json

# Shared Variables
@groupId = b2a1f60c-8f45-4c69-a123-9d79dfefcc65
@chargeStationId = 8c3d486c-02db-4d9d-8f7b-f3c91d334ccc
@connectorId = 1

### 1. Create Group
# Creates a new group with an optional charge station and its connectors
POST {{host}}/api/v1/groups
Content-Type: {{content-type}}

{
  "name": "Test Group",
  "capacityInAmps": 100,
  "chargeStation": {
    "id": "{{chargeStationId}}",
    "name": "Station A",
    "connectors": [
      {
        "id": 1,
        "maxCurrentInAmps": 30
      },
      {
        "id": 2,
        "maxCurrentInAmps": 20
      }
    ]
  }
}


### 2. Update Group
# Updates the name and capacity of an existing group
PUT {{host}}/api/v1/groups/{{groupId}}
Content-Type: {{content-type}}

{
  "name": "Updated Group Name",
  "capacityInAmps": 120
}


### 3. Remove Group
# Removes an existing group along with all its charge stations and connectors
DELETE {{host}}/api/v1/groups/{{groupId}}


### 4. Add Charge Station to Group
# Adds a new charge station with connectors to an existing group
POST {{host}}/api/v1/groups/{{groupId}}/charge-stations
Content-Type: {{content-type}}

{
  "chargeStationId": "{{chargeStationId}}",
  "name": "New Station",
  "connectors": [
    {
      "connectorId": 1,
      "maxCurrentInAmps": 15
    },
    {
      "connectorId": 2,
      "maxCurrentInAmps": 20
    }
  ]
}


### 5. Remove Charge Station from Group
# Removes a specific charge station from the specified group
DELETE {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}


### 6. Add Connector(s) to Charge Station
# Adds one or more connectors to a charge station in an existing group
POST {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/connectors
Content-Type: {{content-type}}

{
  "connectors": [
    {
      "connectorId": 3,
      "maxCurrentInAmps": 25
    },
    {
      "connectorId": 4,
      "maxCurrentInAmps": 10
    }
  ]
}

### 7. Remove Connector(s) from Charge Station
# Removes one or more connectors from a charge station in an existing group
DELETE {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/connectors
Content-Type: {{content-type}}

{
  "connectorIds": [1, 2]
}

### 8. Update Connector Max Current
# Updates the maximum current (in amps) of a specific connector in a charge station within a group
PUT {{host}}/api/v1/groups/{{groupId}}/charge-stations/{{chargeStationId}}/connectors/{{connectorId}}/current
Content-Type: {{content-type}}

{
  "newCurrentInAmps": 40
}


### 9. Get Group By Id
# Retrieves the details of a Group by its ID, including associated charge stations and connectors
GET {{host}}/api/v1/groups/{{groupId}}
Content-Type: {{content-type}}


### 10. Get Groups By Page
# Retrieves a list of groups by specifying page number and page size
GET {{host}}/api/v1/groups/pages?pageNumber=1&pageSize=5
Content-Type: {{content-type}}
